# Generated by Django 4.0.4 on 2022-05-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('idJuego', models.AutoField(primary_key=True, serialize=False)),
                ('tituloJuego', models.CharField(max_length=50, verbose_name='Titulo juego')),
                ('textoJuego', models.CharField(max_length=200, verbose_name='La descripcion')),
                ('precioJuego', models.IntegerField(verbose_name='Precio del juego')),
                ('fotoJuego', models.ImageField(upload_to='Juegos')),
                ('linkJuego', models.CharField(max_length=300, verbose_name='Link del juego')),
                ('plataforma', models.CharField(max_length=20, verbose_name='Plataforma')),
            ],
        ),
    ]
