# Generated by Django 4.0.4 on 2022-05-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrayTheNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de rol')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del tipo de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('idStatus', models.AutoField(primary_key=True, serialize=False, verbose_name='Status de comentario/publicacion *baneo')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre del Status')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPubli',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False, verbose_name='codigo del tipo de la publicacion')),
                ('nombreTipo', models.CharField(max_length=30, verbose_name='Tipo de publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del usuario')),
                ('nombreCompleto', models.CharField(max_length=30, verbose_name='Nombre del usuario')),
                ('correo', models.EmailField(max_length=80, verbose_name='Correo Electronico')),
                ('clave', models.CharField(max_length=200, verbose_name='Contrasenna')),
                ('nickname', models.CharField(max_length=50, verbose_name='Nombre usuario')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('linkInstagram', models.CharField(blank=True, max_length=100, verbose_name='Redes sociales intagram')),
                ('linkTwitch', models.CharField(blank=True, max_length=100, verbose_name='Redes sociales twitch')),
                ('linkTwitter', models.CharField(blank=True, max_length=100, verbose_name='Redes sociales twitter')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrayTheNews.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('idPublicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la publicacion')),
                ('fotoPortada', models.ImageField(upload_to='Foto_Portada')),
                ('tituloPubli', models.CharField(max_length=200, verbose_name='Titulo de la publicacion')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion de la publicacion')),
                ('fechaP', models.DateField(verbose_name='Fecha de la publicacion')),
                ('conclusionP', models.CharField(blank=True, max_length=900, verbose_name='Conclusion Opcional')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrayTheNews.status', verbose_name='Baneo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrayTheNews.tipopubli', verbose_name='Tipo de publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrayTheNews.usuario', verbose_name='Autor de la publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Parrafo',
            fields=[
                ('idParrafo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código del parrafo')),
                ('tituloParrafo', models.CharField(max_length=200, verbose_name='Titulo del parrafo')),
                ('descripcion', models.TextField(blank=True, max_length=2000, verbose_name='Descripcion del parrafo')),
                ('fotoParrafo', models.ImageField(upload_to='Foto_del_parrafo')),
                ('idPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrayTheNews.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False, verbose_name='id comentario')),
                ('descripcion', models.TextField(max_length=550, verbose_name='Contenido de comentario')),
                ('fechaComentario', models.DateField()),
                ('idPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrayTheNews.publicacion', verbose_name='Id publicacion')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrayTheNews.status', verbose_name='Baneo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrayTheNews.usuario', verbose_name='Usuario que comento')),
            ],
        ),
    ]
