# Generated by Django 4.0.4 on 2022-05-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrayTheNews', '0002_rol_status_tipopubli_usuario_publicacion_parrafo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='NickName'),
        ),
    ]
