# Generated by Django 4.0.4 on 2022-05-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrayTheNews', '0003_alter_usuario_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=40, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(max_length=15, verbose_name='NickName'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombreCompleto',
            field=models.CharField(max_length=40, verbose_name='Nombre del usuario'),
        ),
    ]
