# Generated by Django 4.0.4 on 2022-05-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrayTheNews', '0004_alter_usuario_correo_alter_usuario_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fotoUsuario',
            field=models.ImageField(default='media/users/user_default_profile.png', upload_to='Foto de Usuarios'),
        ),
    ]
